### ISSUE TITLE
unsafe.cursor does not work

### ISSUE THREAD

**Issue by MPvHarmelen** [porsager/postgres#149]
When using `cursor` on a query created using `unsafe`, nothing happens: it never resolves and never calls the argument to `cursor`. See my MWE below:

```js
const p = require("postgres");
const q = p("postgresql://postgres:example@localhost/demo");

// this works and prints every row
console.log("a:")
const a = q`select * from "aircrafts"`.cursor(async (row) => {
  console.log(row);
});

setTimeout(() => {
  // this never calls the argument to `cursor` and never resolves
  console.log("b:")
  const b = q.unsafe('select * from "aircrafts"').cursor(async (r) => console.log(r));
}, 1000);
```

<details><summary>Setting up</summary>

```yml
# docker-compose.yml
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
```

- Start postgres

```
mkdir -p ~/postgres/data
# copy above docker-compose.yml to ~/postgres/docker-compose.yml
cd ~/postgres;
docker-compose up -d;
```

- Add a database called `demo` to postgres

```
docker-bash
# select the postgres db container
# install some dependencies
apt update
apt install curl unzip -y
# download a test db dump
curl https://edu.postgrespro.com/demo-small-en.zip > demo.zip
unzip demo.zip
# restore the test db
PGPASSWORD=example psql --username=postgres  -f demo-small-en-20170815.sql
```
</details>
