### ISSUE TITLE
Final rows lost with batch mode of PendingQuery.cursor

### ISSUE THREAD

**Issue by MPvHarmelen** [porsager/postgres#150]
If the number of results isn't divisible by the batch size, the last (and incomplete) batch is never processed:

```js
const p = require("postgres");
const q = p("postgresql://postgres:example@localhost/demo");

// this works and prints all 9 rows
console.log("a:")
const a = q`select * from "aircrafts"`.cursor(console.log)

setTimeout(() => {
  // this only prinst the first 5 rows
  console.log("b:")
  const b = q`select * from "aircrafts"`.cursor(5, console.log);
}, 1000);

setTimeout(() => {
  // this only prinst the first 8 rows
  console.log("c:")
  const c = q`select * from "aircrafts"`.cursor(2, console.log);
}, 2000);

setTimeout(q.end, 3000)
```

<details><summary>Setting up</summary>

```yml
# docker-compose.yml
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
```

- Start postgres

```
mkdir -p ~/postgres/data
# copy above docker-compose.yml to ~/postgres/docker-compose.yml
cd ~/postgres;
docker-compose up -d;
```

- Add a database called `demo` to postgres

```
docker-bash
# select the postgres db container
# install some dependencies
apt update
apt install curl unzip -y
# download a test db dump
curl https://edu.postgrespro.com/demo-small-en.zip > demo.zip
unzip demo.zip
# restore the test db
PGPASSWORD=example psql --username=postgres  -f demo-small-en-20170815.sql
```
</details>
